services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: picpira
      MYSQL_USER: picpira
      MYSQL_PASSWORD: picpira
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: